### ISSUE TITLE
publish binary payload got error

### ISSUE THREAD

**Issue by alloyfang** [emqx/emqx-web-hook#103]
When I send a binary message, the byte value bigger than 0xf7 will change to 0xef 0xbf 0xbd in web hook, for example, I send <<0x53 0x80 0x53>> but payload will get <<0x53 0xef 0xbf 0xbd 0x53>>. but at same time a client subscribe the topic will get correct payload.

I read the code of web hook, It is simple and do not process the parameter, so I think maybe the problem is at emqx.

test at 3.0.0 and 3.1-beta2

reproduce the error

set up an emqx server and config web hook, use mosquito send a binary file 0x53 0x80 0x53, use wireshark catch http package and payload change to 0x53 0xef 0xbf 0xbd 0x53. below is the screen capture.

https://www.alloyfang.com/assets/emqx_web_hook.jpg

**Comment by alloyfang** [comment]
3.1.0 has been released, but this problem is still there.

**Comment by alloyfang** [comment]
3.1.0 has been released, but this problem is still there.

**Comment by Gilbert-Wong** [comment]
@alloyfang , thanks for your feedback. We'll check it if it is a bug.

**Comment by HJianBo** [comment]
Hi, @alloyfang we have added the `web.hook.encode_payload` option in the `emqx_web_hook.conf` to encode the payload field of message

i.e:
```properties
web.hook.encode_payload = base64
```

**Comment by alloyfang** [comment]
thanks a lot, I will have a try after that.

**Comment by alloyfang** [comment]
it seems to work fine with base64 encode
