### ISSUE TITLE
Need explicit disable some webhook event when use docker environment configure

### ISSUE THREAD

**Issue by aaftio** [emqx/emqx-web-hook#108]
I have look this issues #60 , the answer is work when use config file. But when use docker to run, the best way to configure is use docker environment parameters, just like:

-e EMQX_WEB__HOOK__API__URL=http://127.0.0.1:8080/api/open/mqtt/webhook \
-e EMQX_WEB__HOOK__RULE__CLIENT__CONNECTED__1={"action":"on_client_connected"} \
-e EMQX_WEB__HOOK__RULE__CLIENT__DISCONNECTED__1={"action":"on_client_disconnected"}
................

If some hook events not specific by environment parameters, EMQX will take the items in the config file instead. So how can I disable some hook events but not need to change the default plugin config file?

**Comment by zhanghongtong** [comment]
@aaftio We are currently unable to disable the emqx_web_hook.conf configuration via environment variables in docker. You can try to write emqx_web_hook.conf yourself and mount it in the container.

**Comment by aaftio** [comment]
Ok, thanks!
