### ISSUE TITLE
[Feature] Add a configuration option to set "secret" or "token" to be sent with webhook request in HTTP header

### ISSUE THREAD

**Issue by daadu** [emqx/emqx-web-hook#160]
add a configuration option to set "secret" or "token" to be sent with webhook request in HTTP header

**Comment by daadu** [comment]
This feature with #26 would make the webhook requests secure to be sent to 3rd party services

**Comment by emqplus** [comment]
@tigercl Pls create a card for the feature on trello. @daadu Thanks.

**Comment by daadu** [comment]
I can see the option to add a custom header in dashboard though

![Screenshot from 2019-12-11 10-40-02](https://user-images.githubusercontent.com/4963236/70593352-ba570980-1c02-11ea-969c-435647c6c3fb.png)

Is the same thing possible with conf file? if yes then should be mentioned in Doc

**Comment by wivwiv** [comment]
Configuration of HTTP request header of emqx web hook plug-in is coming.
The webhook in Rule Engine supports the configuration through your screenshot. Thank you we will improve the doc.
@daadu

**Comment by notjulian** [comment]
> Configuration of HTTP request header of emqx web hook plug-in is coming.
> The webhook in Rule Engine supports the configuration through your screenshot. Thank you we will improve the doc.
> @daadu

hi
any news on this?
is it available with conf file?

thanks

**Comment by HJianBo** [comment]
Hi @notjulian Thanks for your feedback.  We will implement it in 4.2.0 :)

**Comment by daadu** [comment]
@notjulian As mentioned above Rule Engine with WebHook Action is a good alternative

**Comment by notjulian** [comment]
> @notjulian As mentioned above Rule Engine with WebHook Action is a good alternative

thanks ... but since that rule engine config is stored in mnesia db, if you run emqx with docker isn't easy to persist the data [89](https://github.com/emqx/emqx-docker/issues/89)

**Comment by HJianBo** [comment]
Hi guys. it has released at v4.2-alpha.2. Thanks for your feedback :)
