### ISSUE TITLE
Callbacks not begin invoked by emqx_web_hook plugin  

### ISSUE THREAD

**Issue by sreedevigattu** [emqx/emqx-web-hook#176]
**What I want to achieve?**  Receive the messages from emqx using emqx_web_hook plugin for further processing

**What I did so far?**
- Running a flask based restapi server at http://127.0.0.1:5000
- The restapi server responds to the following http requests curl http://127.0.0.1:5000/, curl http://127.0.0.1:5000?, curl http://127.0.0.1:5000/?p1=1,p2=2, curl -d '{"id":1,"name":"abc"}' -H 'Content-Type: application/json' http://localhost:5000/
- Updated etc/emqx/plugins/emqx_web_hook.conf web.hook.api.url = http://127.0.0.1:5000 (rest of the file is unchanged) and restarted emqx broker
- Opened port 5000
- Run test mqtt publisher and subscriber. The published messages are received by the subscriber.

**What is the issue?** The restapi server does not receive any of the published messages.  

Any hints to debug this issue. 
_Please note that I am relatively new to the restapi space, so there could be basic misses in what I have done._

**Comment by sreedevigattu** [comment]
Meanwhile I fugured out the issue. I had missed out doing this
emqx_ctl plugins load emqx_web_hook

Now I receive the callbacks

**Comment by HJianBo** [comment]
Haha, @sreedevigattu So I'll close this issue.

If you have any questions, let me known or open a new one
