### ISSUE TITLE
Connection to emqx using websockets is delayed

### ISSUE THREAD

**Issue by sreedevigattu** [emqx/emqx-web-hook#184]
When I try to connect to the emqx broker using websockets, there is 30sec delay. With tcp the connection is immediate. Is there a way to remove the delay?

05:45:**24**: Trying to connect to localhost:8083
05:45:24: client.connect call made with mqtt.Client.connect params _--> after client.connect_
      _host=localhost _port=8083
      _websocket_path:/mqtt _transport:websockets
      _client_id: abc 
05:45:**54**: CONNECTED WITH RESULT CODE: 0 _--> in on_connect_
05:45:54: SUBSCRIBED FOR $ABC/#

**Comment by HJianBo** [comment]
Could you paste the emqx version?

And Plz try to capture the websocket traffic to analyze the blocked

**Comment by sreedevigattu** [comment]
emqx vversion   : 4.0.5

I tried a couple of scenarios:
**Client to local emqx** - _This connected after 30 seconds_
**Client to remote emqx**  _This connected immediately_ 
See below the traces from my clients
My client is a python client. Which tool can be used to capture websocket traffic to analyze the traffic between the client and server **on the same host**?

**Client to remote emqx** - _Connected immediately_ 
(venv)# python emqxclient_ws.py A.B.C.D websockets y
05:29:51: Trying to connect to A.B.C.D:8083
05:29:51: client.connect call made with mqtt.Client.connect params
_host=172.31.26.251 _port=8083
_websocket_path:/mqtt _transport:websockets
_username: dummy  _password: dummy
05:29:51: PUBLISHING messages
: $ABC
05:29:52: CONNECTED WITH RESULT CODE: 0. 
05:29:52: SUBSCRIBED FOR $ABC/#
: $ABC hello

**Client to local emqx** - _Connected after 30 seconds_
(venv)# python emqxclient_ws.py localhost websockets y
05:33:46: Trying to connect to localhost:8083
05:**33:46**: client.connect call made with mqtt.Client.connect params
_host=localhost _port=8083
_websocket_path:/mqtt _transport:websockets
_username: dummy  _password: dummy
05:33:46: PUBLISHING messages
: $ABC
05:**34:16**: CONNECTED WITH RESULT CODE: 0  
05:34:16: SUBSCRIBED FOR $ABC/#

**Comment by sreedevigattu** [comment]
We had a authentication plugin that was trying to connect to a mongo db that was failing sometimes due to which the above error was observed.
