### ISSUE TITLE
webhook generates empty post

### ISSUE THREAD

**Issue by victorclaessen** [emqx/emqx-web-hook#186]
emqx 4.0.6

I am trying to get webhooks working, but am having an issue. Perhaps I do not understand what exactly I have to do. The documentation is not sufficient for me.

I have been able to make emqx republish data on another mqtt topic using rules, but not post it to a webhook. I will explain the steps I have taken.

Using the EMQ dashboard, I make a rule with the SQL `"SELECT payload FROM "t/#"`. I then add an action handler, and select "Data to Web Server" using a previously configured resource (`POST` to `http://localhost/webhook.php`, empty `request header` list). I leave the `Payload Template` field empty.

I have the following `webhook.php`:
```
<?php
file_put_contents("log/post.log", print_r($_POST, true)); 
print "ok";
?>
```

I then post to topic `t/test` a string value of `test`. I can then see in the apache log that emqx has posted to `webhook.php`. The file `log/post.log` has been made. Unfortunately, the contents of the file is the PHP representation of an empty array, _i.e._ the POST was empty.

I was hoping for things like clientid, topic and payload to have been posted.

Can you suggest what I am doing wrong?

Thanks!

**Comment by HJianBo** [comment]
Hi, @victorclaessen Is your message going to be big? There is a BUG in v4.0.6 that causes a large message not to be encoded as JSON. see https://github.com/emqx/emqx/issues/3382

Please you can try the v4.1-alpha.2 version. It may be fixed it.

**Comment by victorclaessen** [comment]
In my case, the message payload was short (the string value "test"), so I'm not sure if the bug affects this situation.

Could you possibly comment on my test strategy? Am I doing things right generally?

I will try to get the alpha version.

**Comment by victorclaessen** [comment]
I'm sorry. My understanding of parsing POST data in PHP was wrong. EMQ _is_ posting all the variables as json. PHP just doesn't get json data like it does HTML form data (as explained [here](https://stackoverflow.com/questions/16868120/accessing-posted-json-data-in-php-script)). When I changed my webhook.php to the following, I got my json formatted data:
```
<?php
$name=$_SERVER[UNIQUE_ID];
file_put_contents("webhooklog/post.$name.log", file_get_contents("php://input"));
print "ok";
?>
```

The data in the log file was:
```
{"username":"undefined","topic":"t/test","timestamp":1587891259502,"qos":0,"publish_received_at":1587891259502,"peerh
ost":"127.0.0.1","payload":"TEST","node":"emqx@REDACTEDHOSTNAME","msg":"TEST","id":"5A42DBE76EE02A1
D6490031280001","headers":{"username":"undefined","protocol":"mqtt","proto_ver":4,"peerhost":"127.0.0.1"},"flags":{"r
etain":false,"dup":false},"event":"message.publish","clientid":"mosq-SplOK4c5Z2Fgr1HWCZ"}
```

I will now go on to try and figure out how to format the json data. I did not find anything about the formatting in the documentation. If I cannot get it to work, I will open a new issue.

Sorry to bother you with this.
