### ISSUE TITLE
Client ID is blank

### ISSUE THREAD

**Issue by ChinaChenjinlin** [emqx/emqx-web-hook#191]
hello,  Sometimes the client Id obtained through webhook is null. why?

**Comment by ChinaChenjinlin** [comment]
![图片](https://user-images.githubusercontent.com/44959543/82643379-f9719800-9c41-11ea-8e67-a530585a6ec2.png)

The client ID selected in the red box is null

**Comment by HJianBo** [comment]
Hi, @ChinaChenjinlin I can understand that.

The webhook just pass all client events to a backend server, it should not modify any data for the client.
