### ISSUE TITLE
Confusion regarding emqx-rule-engine

### ISSUE THREAD

**Issue by daadu** [emqx/emqx-web-hook#196]
`emqx-web-hook` and `emqx-rule-engine` have overlapping use cases. For example processing all messages published by web server can be done by both the plugin.

Can some from @emqx clarify the following:
- Which one the plugin is recommended for it?
- Performance wise which is better?
- Does any one of it implement "fire and forget" mechanism for sending messages to web server instead on syncronously waiting for response?
- Since it looks redundant which one of the plugin will be in active development, is there any plan to deprecate `emqx-web-hook` in favour of `emqx-rule-engine`?

**Comment by HJianBo** [comment]
No, these two plugins are fundamentally different, Even if they can deal with some kind of special user scenarios.

The `emqx_web_hook` focuses on forwarding the Broker event to a webserver directly. It won't modify the event's data and information. Just forwarding it. This is the biggest difference between and rule engine.

The `emqx-rule-engine` emphasizes the Rules. It can change the structure of a message, or pick up some field data for an event in your requirements.

It's more powerful than `emqx-web-hook`. But `emqx-web-hook` is necessary for some simple or fundamental user scenarios.

-------------

>  Which one the plugin is recommended for it?

it depends on your requirement. If you need simply forwarding,  `emqx-web-hook` is advisable.

> Performance wise which is better?

There should be no apparent difference

> ... "fire and forget" mechanism ...

They don't support now. We have a plan at v4.2.0

> is there any plan to deprecate emqx-web-hook ...

Nope.

**Comment by daadu** [comment]
@HJianBo Thanks for the clarify. I guess this should be documented somewhere - in emqx blogs or tutorial.

Thanks. Closing this issue.

**Comment by daadu** [comment]
Re-opening since this is added to https://github.com/emqx/emqx-web-hook/milestone/53. milestone
