### ISSUE TITLE
Dynamically create a request URL (when combined with Rule Engine)

### ISSUE THREAD

**Issue by z8674558** [emqx/emqx-web-hook#224]
**It would be nice if the action's request URL is generated based on the topic which the rule is listening to.**

e.g. Suppose a device is publishing its state, to the topic 'deviceid/stateid'. Sometimes you want to forward the message to a HTTP server to do something with that data. In this case it is helpful for message to be forwarded to "http://example.com/deviceid/stateid".

I think this feature is possible by adding a function something like this:

```
complete_url(Url, Topic) ->
    TopicTokens = string:tokens(Topic, "/"),
    TopicTokensArray = array:from_list(TopicTokens),
    complete_url(Url, TopicTokensArray, length(TopicTokens), 0).

complete_url(Url, _, MaxIdx, MaxIdx) ->
    Url;

complete_url(Url, Array, MaxIdx, Idx) ->
    Placeholder = "\\{" ++ integer_to_list(Idx) ++ "\\}",
    complete_url(re:replace(Url, Placeholder, array:get(Idx, Array), [global, {return, list}]), Array, MaxIdx, Idx+1)
```

If you pass "http://example.com/{0}/{1}/{2}/{0}" as a request URL and the topic is "aa/bb/cc", "http://example.com/aa/bb/cc/aa" is generated.

**Comment by terry-xiaoyu** [comment]
@z8674558 

Thanks! After changing the code, we have to update the appup file: `https://github.com/emqx/emqx-web-hook/blob/master/src/emqx_web_hook.appup.src`.

We could hot upgrade emqx using `emqx_ctl install <Version>`.
