### ISSUE TITLE
publish payload with protocolbuf got errors

### ISSUE THREAD

**Issue by edwardhey** [emqx/emqx-web-hook#36]
FYI.

2018-01-22 10:17:09.765 [error] <0.11133.0> gen_server <0.11133.0> terminated with reason: no function clause matching mochijson2:json_encode_string_unicode({error,"\b",<<199,1,21,189,55,134,54,29,172,197,167,54>>}, {encoder,null,false}, "\"") line 300
2018-01-22 10:17:09.765 [error] <0.11133.0> CRASH REPORT Process <0.11133.0> with 0 neighbours exited with reason: no function clause matching mochijson2:json_encode_string_unicode({error,"\b",<<199,1,21,189,55,134,54,29,172,197,167,54>>}, {encoder,null,false}, "\"") line 300 in gen_server2:terminate/3 line 1157
2018-01-22 10:17:09.765 [error] <0.1427.0> Supervisor 'esockd_connection_sup - <0.1427.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.11133.0> exit with reason no function clause matching mochijson2:json_encode_string_unicode({error,"\b",<<199,1,21,189,55,134,54,29,172,197,167,54>>}, {encoder,null,false}, "\"") line 300 in context connection_crashed

Thanks.

**Comment by emqplus** [comment]
@edwardhey Publish using the HTTP API?

**Comment by edwardhey** [comment]
I use golang [client](https://github.com/eclipse/paho.mqtt.golang),and pack msg with google protobufcol

**Comment by funwun** [comment]
I got the same bug
the reason is:
https://github.com/basho/mochiweb/blob/master/src/mochijson2.erl#L300

**Comment by rudylacrete** [comment]
Any progress on this issue? In my opinion, using the JSON encoding for http requests is a mistake because MQTT payload need to be considered as binary data which can't be encoded in JSON. Using BSON may be a better solution

**Comment by terry-xiaoyu** [comment]
@rudylacrete Are you using TCP or WebSocket? You only packed the MQTT body using protobuf? Does the encoding error only occur when you publishing a MQTT message?

**Comment by rudylacrete** [comment]
I'm using TCP. For my part I'm not using protobuf but I'm using my own binary protocol. The payload sent by the mqtt client is raw binary frames which is not valid UTF8 or Latin encoding. The encoding error only occurs when publishing because the plugin try to create a http request using json encoding where the payload is a binary buffer with no valid UTF8 caracters. This is why I think using BSON for exemple could fix this problem. Or maybe just skip the payload if we can't encode it to JSON and add an extra error code within the final JSON sent in the http request

**Comment by terry-xiaoyu** [comment]
@rudylacrete Thanks for your explanation. We plan to fix this issue in MQTT 2.4 (the current version is 2.3.6).

**Comment by rudylacrete** [comment]
You're welcome. Any schedule for this version 2.4?

**Comment by public2** [comment]
I have the same problem. How did you solve it?Is that a problem now?

**Comment by rudylacrete** [comment]
I modified the webhook plugin to catch json encoding error and return null in this case but there is no official patch for this problem. I didn't check if the issue still exists in version 3 of EMQ.

**Comment by public2** [comment]
Can you share the modified code? How is the modified plugin source code compiled into the server?Thank you very much

**Comment by public2** [comment]
> I modified the webhook plugin to catch json encoding error and return null in this case but there is no official patch for this problem. I didn't check if the issue still exists in version 3 of EMQ.

Can you share the modified code? How is the modified plugin source code compiled into the server?Thank you very much

**Comment by public2** [comment]
@rudylacrete Can you share the modified code? How is the modified plugin source code compiled into the server?Thank you very much

**Comment by rudylacrete** [comment]
I've forked the repository and made the following update:
https://github.com/rudylacrete/emq-web-hook/commit/1acc13e6f81b2f424f60592aa56c525f316fa886

Then you just have to update the Makefile of the emqx project in using the correct github URL and rebuild the project from source.

**Comment by Gilbert-Wong** [comment]
We have deprecated mochiweb to decode and encode json in emqx3.0. Now we use jsx to encode and decode json, could you please try with the latest emqx3.0?
