### ISSUE TITLE
Disable some webhook event

### ISSUE THREAD

**Issue by abser** [emqx/emqx-web-hook#60]
@s4kibs4mi ,
Is it possible to disable some webhook rule? For example, I want to receive webhook for below 2 actions only. Other actions I want to disable. I use webhook to persist the client messages in a database and I only need this 2 type of messages.

web.hook.rule.message.publish.1      = {"action": "on_message_publish"}
web.hook.rule.message.delivered.1    = {"action": "on_message_delivered"}

**Comment by s4kibs4mi** [comment]
@abser removing the rule for a specific action should disable the hook.
