### ISSUE TITLE
请问我应改如何使用它

### ISSUE THREAD

**Issue by SammyLee666** [emqx/emqx-web-hook#61]
我现在想上线和下线触发一个回调，但是我不知道如何来实现它

**Comment by SammyLee666** [comment]
我应该如何使用web_hook谢谢

**Comment by Gilbert-Wong** [comment]
English

**Comment by SammyLee666** [comment]
How to receive callbacks, I don't know how to use them.
Thank you

**Comment by SammyLee666** [comment]
Please

**Comment by SammyLee666** [comment]
I followed the documentation, but after that I don't know how to callback, I need to listen for some operations.
---
![image](https://user-images.githubusercontent.com/22285205/44301473-15982500-a34a-11e8-9db8-17eb4fa27890.png)

**Comment by Gilbert-Wong** [comment]
What callbacks ? I do not understand what you mean.

**Comment by SammyLee666** [comment]
For example, I need to write to the database when `on_client_connected`.

**Comment by SammyLee666** [comment]
Please, this problem has been bothering me for a few days. If it can be solved, it is really great.

**Comment by Gilbert-Wong** [comment]
When the states of emq changed, it would send a http request to you http server . It is your job to implement your database action.

**Comment by Gilbert-Wong** [comment]
So strange the issue you opened.

**Comment by SammyLee666** [comment]
Writing to the database is my accusation. How does the http server receive the request?
---
![image](https://user-images.githubusercontent.com/22285205/44301576-0e721680-a34c-11e8-8a67-8afe428fafb3.png)

**Comment by SammyLee666** [comment]
Is the GET method?

**Comment by Gilbert-Wong** [comment]
No, POST

**Comment by SammyLee666** [comment]
Seems to understand, this is the parameter POST passed.
```
{
    "action":"client_connected",
    "client_id":"C_1492410235117",
    "username":"C_1492410235117",
    "conn_ack":0
}
```

Thank you for solving my doubts, thanks to open source.
