### ISSUE TITLE
HTTP 422

### ISSUE THREAD

**Issue by jhserodio** [emqx/emqx-web-hook#65]
http status code 422, is not treated as error in send_http_request

**Comment by Gilbert-Wong** [comment]
Sorry, could you give me more details? When and how did you trigger this problem.

**Comment by jhserodio** [comment]
yes, sorry.

The application does not treat any http status code, the 'httpc:request' function resolve any status code with atom 'ok', and status code could be fixed in send_http_request.

**Comment by Gilbert-Wong** [comment]
No, the `httpc:request` would return a status code if request error, the status code returned depends on the http server, so I want to know which edition of emqx did you use, because we have replaced mochiweb with cowboy in emqx3.0.

**Comment by rajivramv** [comment]
My http server returns a 400 status code and `Bad Request` as the response payload for the `client_subscribe` hook. The broker however allows the subscription. 

```
$ ./bin/emqx_ctl status
Node 'emqx@127.0.0.1' is started
emqx 3.0 is running
```

**Comment by rajivramv** [comment]
Is it possible to cancel subscription like the lua hook [does](https://github.com/emqx/emqx-lua-hook#on_client_subscribe)?

**Comment by Gilbert-Wong** [comment]
Sorry, it is impossible. The web hook is different from the lua-hook. Lua hook supports you to use lua to write emqx hook plugin, but web hook is a finished plugin. It sends http request when the mqtt events such as connect and subscribe and so on triggered.
