### ISSUE TITLE
support http kafka interface

### ISSUE THREAD

**Issue by jhserodio** [emqx/emqx-web-hook#67]
support for kafka http interface, with dynamic wrapper of request Params

**Comment by Gilbert-Wong** [comment]
Hi, jhserodio, we have kafka plugin for enterprise edition of emqx, please contact with @zhengyupan

**Comment by jhserodio** [comment]
we are considering using web-hook as an interface for many situations, but we also need to be able to modify the private function send_http_request attributes, for 'application type' and 'params', this way we would be able to integrate with Confluent REST Proxy API and others.

**Comment by Gilbert-Wong** [comment]
Using web-hook as an interface for multiple situations is a bad idea because it will waste the advantage of mqtt protocol if you use http interface to operate mqtt broker. The performance would be bad.
