### ISSUE TITLE
Client ID & Username not in message body

### ISSUE THREAD

**Issue by Schweig** [emqx/emqx-web-hook#72]
Hey so when I set up the web-hook plugin to post to a webserver running locally this is the body that I get.
`{"action":"message_publish","from_client_id":"","from_username":"","topic":"data/rand","qos":2,"retain":true,"payload":"145,2018-11-05 18:08:06,34","ts":1541459286}`

I expect this as it shows in the documentation but am not receiving the same information.
```
{
    "action":"message_publish",
    "from_client_id":"C_1492410235117",
    "from_username":"C_1492410235117",
    "topic":"world",
    "qos":0,
    "retain":true,
    "payload":"Hello world!",
    "ts":1492412774
}
```

**Comment by Gilbert-Wong** [comment]
Because when you publish message, you didn't specify client_id and username.

**Comment by Schweig** [comment]
I specify the client id and username when I connect is that not enough? I see a client id on the web dashboard. Do I need to put it as part of the payload? I'm using the eclipse paho c++ library if that helps

**Comment by Gilbert-Wong** [comment]
No, you misunderstand what mqtt protocol is doing. First, the client id is specified in connect packet which is used by your client to connect broker; if you did not specify this field in connect packet sent to broker, the web hook won't post client_id and from_user in the json.

**Comment by Schweig** [comment]
I believe I am specifying this field when i connect.
`{"action":"client_connected","client_id":"demo","username":"demo","conn_ack":0}`
this is what I receive from the web hook when i connect a client. as you can see i have a username and client_id of demo. Below is a snippet of how i set up my client. 

     mqtt::async_client cli(address, "demo", MAX_BUFFERED_MSGS, PERSIST_DIR);
	mqtt::connect_options connOpts;
	connOpts.set_keep_alive_interval(MAX_BUFFERED_MSGS * PERIOD);
	connOpts.set_clean_session(true);
	connOpts.set_automatic_reconnect(true);
    connOpts.set_user_name("demo");

**Comment by Gilbert-Wong** [comment]
I use websocket interface of dashboard to publish message, this is my result:
![image](https://user-images.githubusercontent.com/20479699/48103484-51b49500-e26a-11e8-9d65-15463544c149.png)

It must something wrong happened on your code or your mqtt client library.

**Comment by Schweig** [comment]
`{"action":"message_publish","from_client_id":"","from_username":"","topic":"/World","qos":0,"retain":false,"payload":"Hello world!","ts":1541552767}`

even using the dashboard I don't get anything. I'm going to install emqx on a linux vm and see if that changes anything right now I'm using windows.

**Comment by Gilbert-Wong** [comment]
Sorry for that, windows package of emqx always has some odd problems. We would fix it in emqx3.0.

**Comment by Gilbert-Wong** [comment]
By the way, next time you opened issue, you should tell me which emqx version you used and which platform package you use.

**Comment by Schweig** [comment]
no worries was just using the windows to try emqx out any projects i would build with it would be in a linux environment. thanks so much for all your help. Yeah next time ill keep that in mind thanks again

**Comment by Schweig** [comment]
Hey coming back from a clean ubuntu 18.04 vm installing EMQX with the ubuntu .deb for the v3.0-beta.3 I'm still having this problem.

![virtualbox_ubun_08_11_2018_13_09_11](https://user-images.githubusercontent.com/6835709/48218317-9bc77480-e357-11e8-925c-0701a7e96e5d.png)

Is there any information that I could send you to help get this problem resolved. I am unsure of what I am doing wrong.

**Comment by Gilbert-Wong** [comment]
Which version of emqx do you use? Please try with the latest emqx3.0-rc3

**Comment by Schweig** [comment]
So I just downloaded the rc3 zip unziped it and started emqx with the console option. When I connected via the websocket and sent a message this is what my console looked like.

```
./bin/emqx console
Exec: /home/ubuntu/Downloads/emqx/erts-10.0.5/bin/erlexec -boot /home/ubuntu/Downloads/emqx/releases/3.0/emqx -mode embedded -boot_var ERTS_LIB_DIR /home/ubuntu/Downloads/emqx/erts-10.0.5/../lib -mnesia dir "/home/ubuntu/Downloads/emqx/data/mnesia/emqx@127.0.0.1" -config /home/ubuntu/Downloads/emqx/data/configs/app.2018.11.12.11.32.11.config -args_file /home/ubuntu/Downloads/emqx/data/configs/vm.2018.11.12.11.32.11.args -vm_args /home/ubuntu/Downloads/emqx/data/configs/vm.2018.11.12.11.32.11.args -- console
Root: /home/ubuntu/Downloads/emqx
/home/ubuntu/Downloads/emqx
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:32] [hipe]

Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8080 successfully.
Start http:dashboard listener on 18083 successfully.
Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
Start mqtt:ws listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
Start mqtt:wss listener on 0.0.0.0:8084 successfully.
EMQ X Broker 3.0-rc.3 is running now!
Eshell V10.0.5  (abort with ^G)
(emqx@127.0.0.1)1> 2018-11-12 11:33:42.688 [error] mqttjs_9838119c09 WebHook: HTTP request error: {failed_connect,
                                 [{to_address,{"127.0.0.1",8082}},
                                  {inet,[inet],econnrefused}]}
2018-11-12 11:33:42.689 [error] mqttjs_9838119c09@127.0.0.1:59908 WebHook: HTTP request error: {failed_connect,
                                 [{to_address,{"127.0.0.1",8082}},
                                  {inet,[inet],econnrefused}]}
```

**Comment by Schweig** [comment]
no i dont have my problem solved. it would be nice to have this feature but ive jsut been passing the client id/ username in the payload. If I solve anything ill add it to the open issue you have

**Comment by Soram-jxx** [comment]
I don't think it's a good way to put it on the payload, but it can only be solved now.
