### ISSUE TITLE
the field of from_client_id and from_username is null

### ISSUE THREAD

**Issue by Soram-jxx** [emqx/emqx-web-hook#75]
emqx version : emqx-3.0-rc.3；

**Comment by Soram-jxx** [comment]
{action":"message_publish","from_client_id":"","from_username":"","topic":"100000000018330010","qos":2,"retain":false,"payload":"123456","ts":1542088012}

**Comment by Soram-jxx** [comment]
![image](https://user-images.githubusercontent.com/22890470/48394423-7fa84680-e74e-11e8-9daa-9b1bfc9fef9e.png)
![image](https://user-images.githubusercontent.com/22890470/48394439-9058bc80-e74e-11e8-96e9-e71b83356dd6.png)

**Comment by Soram-jxx** [comment]
I also tried using the latest version of EMQX. The from_client_id and from_username are empty in the json data of the published data.

**Comment by Gilbert-Wong** [comment]
@Soram-jxx what is the mqtt client you use ?

**Comment by Soram-jxx** [comment]
Eclipse Paho MQTT Utility .

**Comment by Soram-jxx** [comment]
@Gilbert-Wong 
![image](https://user-images.githubusercontent.com/22890470/48399181-e6812c00-e75d-11e8-988c-df67ab6873dc.png)

**Comment by Soram-jxx** [comment]
@Gilbert-Wong I changed MQTT client to Eclipse Paho MQTT ,this probelm also exist.

**Comment by Soram-jxx** [comment]
@Gilbert-Wong Is this question confirmed?

**Comment by pradyum** [comment]
I tried with web dashboard websocket , even on that the same bug is produced.
from_username and from_client_id are null all the time.

**Comment by Gilbert-Wong** [comment]
@Soram-jxx @pradyum Thanks your guys' feedback! I have reproduce it successfully, and it would be fixed in the emqx3.0.0 release.

**Comment by Soram-jxx** [comment]
well！I look forward to your release of the new patch as soon as possible。

**Comment by Soram-jxx** [comment]
@Gilbert-Wong How to compile the latest code into the server？

**Comment by s4kibs4mi** [comment]
@Soram-jxx either choose latest branch of emqx-rel or update version of dependencies if you are working on a specific branch. Latest release is `3.0-rc.4`.

**Comment by marvinkruse** [comment]
Thanks for fixing this @Gilbert-Wong , with the latest version of this plugin the from_client_id is now correctly set. But after upgrading the web hook plugin I wasn't able to publish via the dashboards HTTP API anymore. Publishes via web socket/regular client work for me, but publishing over the dashboard HTTP API produces the following error:

Publish to `127.0.0.1:18083/api/v3/mqtt/publish` with valid basic authentication (admin:public) sending JSON: `"{"topic": "testtopic", "payload": "hello", "qos": 1, "retain": true, "client_id":mqttjs_ab9069449e"}` returns an `Internal Error`

The log of the broker shows:

```
2018-11-30 13:05:59.556 [error] POST /api/v3/mqtt/publish error: function_clause, stacktrace:
[{emqx_web_hook,format_from,
                [{message,<<0,5,123,224,159,84,118,22,244,66,0,0,8,121,0,0>>,
                          1,<<"mqttjs_ab9069449e">>,
                          #{retain => true},
                          #{},<<"testtopic">>,<<"hello">>,
                          {1543,579559,556628}}],
                [{file,"src/emqx_web_hook.erl"},{line,278}]},
 {emqx_web_hook,'-on_message_publish/2-fun-0-',2,
                [{file,"src/emqx_web_hook.erl"},{line,175}]},
 {emqx_hooks,run_,3,[{file,"src/emqx_hooks.erl"},{line,105}]},
 {emqx_broker,publish,1,[{file,"src/emqx_broker.erl"},{line,155}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {emqx_mgmt_api_pubsub,publish,2,
                       [{file,"src/emqx_mgmt_api_pubsub.erl"},{line,68}]},
 {minirest_handler,dispatch,3,[{file,"src/minirest_handler.erl"},{line,55}]},
 {minirest,handle_request,2,[{file,"src/minirest.erl"},{line,66}]}]
```

Any idea why this doesn't work anymore?

**Comment by Gilbert-Wong** [comment]
It has been fixed in emqx3.0.rc.5, please upgrade emqx and try again.
