### ISSUE TITLE
An exception occurred while executing make

### ISSUE THREAD

**Issue by Soram-jxx** [emqx/emqx-web-hook#78]

**Comment by Soram-jxx** [comment]
ERLC   emqx_web_hook.erl emqx_web_hook_app.erl emqx_web_hook_cfg.erl emqx_web_hook_sup.erl
src/emqx_web_hook.erl:17: can't find include lib "emqx/include/emqx.hrl"
src/emqx_web_hook.erl:170: record message undefined
src/emqx_web_hook.erl:172: record message undefined
src/emqx_web_hook.erl:179: record message undefined
src/emqx_web_hook.erl:180: record message undefined
src/emqx_web_hook.erl:181: variable 'Retain' is unbound
src/emqx_web_hook.erl:182: record message undefined
src/emqx_web_hook.erl:183: record message undefined
src/emqx_web_hook.erl:186: variable 'Topic' is unbound
src/emqx_web_hook.erl:192: record message undefined
src/emqx_web_hook.erl:201: record message undefined
src/emqx_web_hook.erl:202: record message undefined
src/emqx_web_hook.erl:203: variable 'Retain' is unbound
src/emqx_web_hook.erl:204: record message undefined
src/emqx_web_hook.erl:205: record message undefined
src/emqx_web_hook.erl:207: variable 'Topic' is unbound
src/emqx_web_hook.erl:213: record message undefined
src/emqx_web_hook.erl:221: record message undefined
src/emqx_web_hook.erl:222: record message undefined
src/emqx_web_hook.erl:223: variable 'Retain' is unbound
src/emqx_web_hook.erl:224: record message undefined
src/emqx_web_hook.erl:225: record message undefined
src/emqx_web_hook.erl:227: variable 'Topic' is unbound
src/emqx_web_hook.erl:278: variable 'From' is unbound
src/emqx_web_hook.erl:278: record message undefined
src/emqx_web_hook.erl:279: record message undefined
src/emqx_web_hook.erl:280: record message undefined
src/emqx_web_hook.erl:281: variable 'ClientId' is unbound
src/emqx_web_hook.erl:281: variable 'Username' is unbound
src/emqx_web_hook.erl:283: Warning: function a2b/1 is unused
make[1]: *** [ebin/emqx_web_hook.app] 错误 1
make: *** [app] 错误 2

**Comment by Gilbert-Wong** [comment]
Please `make` it. This bug fix has been merged into emqx branch, you can try to clone emqx-rel to your local machine, than execute `make`.

**Comment by Soram-jxx** [comment]
Ok, I will try.

**Comment by Soram-jxx** [comment]
@Gilbert-Wong Recompile: src/rebar_rel_utils
Recompile: src/rebar_reltool
Recompile: src/rebar_require_vsn
Recompile: src/rebar_shell
Recompile: src/rebar_subdirs
Recompile: src/rebar_templater
Recompile: src/rebar_upgrade
Recompile: src/rebar_utils
Recompile: src/rebar_xref
==> rebar (compile)
==> rebar (escriptize)
Congratulations! You now have a self-contained script called "rebar" in
your current working directory. Place this script anywhere in your path
and you can use rebar to build OTP-compliant apps.
make[1]: 离开目录“/home/ccicart/tools/software/emqx-web-hook/emqx-rel/.erlang.mk/rebar”
/home/ccicart/tools/software/emqx-web-hook/emqx-rel
 DEP    emqx
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/bin/sh: 第 0 行:cd: /home/ccicart/tools/software/emqx-web-hook/emqx-rel/deps/emqx: 没有那个文件或目录
make: *** [/home/ccicart/tools/software/emqx-web-hook/emqx-rel/deps/emqx] 错误 1

**Comment by Gilbert-Wong** [comment]
Please git clone emqx-rel rather emqx-web-hook.  Then build emqx-rel which include emqx-web-hook.

**Comment by Gilbert-Wong** [comment]
Or you can wait for tommorrow's emqx3.0.0 release.

**Comment by Soram-jxx** [comment]
OK.But I still want to ask that how do I compile the web-hook plugin separately?

**Comment by Gilbert-Wong** [comment]
There two approaches to build emqx-web-hook. First, you can use erlang.mk to make, but you have to rename emqx-web-hook to emqx_web_hook. Second, you can just use rebar3 to make, for example, you could `make rebar-compile`.
