### ISSUE TITLE
About web-hook receiving data from payload

### ISSUE THREAD

**Issue by Soram-jxx** [emqx/emqx-web-hook#79]
How to restore binary data in the web-hook callback interface?

**Comment by Gilbert-Wong** [comment]
Sorry, @Soram-jxx , I don't understand your meaning. Why do you need to restore binary data in the web-hook callback interface?

**Comment by Soram-jxx** [comment]
My amateur need is to determine if the subscriber actually consumes the payload and knows which client is spending.

**Comment by Soram-jxx** [comment]
![image](https://user-images.githubusercontent.com/22890470/49267910-9f05da00-f497-11e8-9dcd-c67306a0bc1f.png)

**Comment by Gilbert-Wong** [comment]
Hi, @Soram-jxx. If you want to ensure that the message would have been consumed by your subscribers, your should use qos >= 1 to subscribe the topic and deliver the message whose qos >= 1  to the topic. The binary data would be sent as http request. If your http packet would haven't been hijacked and falsified, this payload must be consisted with the payload subscriber received.

**Comment by Gilbert-Wong** [comment]
Sorry, I misunderstood what you said. If you want client D to know the who sent message. You could use json string which contains client_id field to let client D know which client sent this message.

**Comment by Soram-jxx** [comment]
I think put the filed of Client_id and Username into payload is unsafe. If I use the solution you said, it does solve the problem. If that's the case, I don't have much meaning using the web-hook plugin.

**Comment by Gilbert-Wong** [comment]
Hi, @Soram-jxx , I have a question. Why do you think it is unsafe ? Web-hook is not designed for distinguishing client_id. Maybe you misunderstand the purpose of emqx-web-hook. In you scenario, I supposed that it is unnecessary for you to use web-hook.
