### ISSUE TITLE
bug when load emqx-web-hook

### ISSUE THREAD

**Issue by Cody1988** [emqx/emqx-web-hook#93]
EMQ v3.0.1 when I enable emqx-web-hook , and set web.hook.api.url=http://127.0.0.1:30041/emqHook ，there is some bugs shown.

For example : 
1. when I publish a message to a topic , It cannot be received; 
2. mqtt.fx connected to emq , when I close my mqtt.fx client the Dashboard also show there is a connected client;
and also some other errors , anybody happens? 

the emqHook is simple

```
@RequestMapping("emqHook")
public Object emqHook(@RequestBody Map<String,Object> params){
    logger.info(params.toString());
    return new HashMap<>();
}
```

**Comment by a181730070** [comment]
I Have the same problems,

**Comment by linjunjj** [comment]
Hi @Cody1988  We are examining the problem.

**Comment by linjunjj** [comment]
@Cody1988  Thank you for feedback，This problem exists and we will fix it.

**Comment by Cody1988** [comment]
@linjunjj ok tks
